# Generated by Django 6.1.1 on 2026-09-28 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('destinations', '0001_initial'),
        ('itineraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['destination', 'accommodation_type'], name='bookings_ac_destina_35e1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['is_available'], name='bookings_ac_is_avai_0ce97e_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['destination', 'category'], name='bookings_ac_destina_923859_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_available'], name='bookings_ac_is_avai_5c69f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'destination')},
        ),
    ]
