# Generated by Django 6.1.1 on 2026-09-28 09:20

import TRAVELAPI.file_validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation')], max_length=20)),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('dry', 'Dry'), ('temperate', 'Temperate'), ('continental', 'Continental'), ('polar', 'Polar')], max_length=20)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('avg_daily_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', validators=[TRAVELAPI.file_validators.validate_upload])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'category'], name='destination_country_c7c612_idx'), models.Index(fields=['climate'], name='destination_climate_5ffe0c_idx'), models.Index(fields=['is_active'], name='destination_is_acti_09f11c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DestinationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_photos/', validators=[TRAVELAPI.file_validators.validate_upload])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='destinations.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
